
## 0 Preparation step
# Create a folder called assignment 2:
```{r}
if(!file.exists("./assignment")){dir.create("./assignment")}
```

# Download and unzip file:
```{r}
fileurl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
download.file(fileurl, destfile = "./assignment/assignment.zip")
unzip(zipfile = "./assignment/assignment.zip", exdir = "./assignment")
```

# Read the file into R and check and class of each variable:
```{r}
setwd("D:/Statistics/R/R data/assignment2/assignment")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
lapply(NEI, class); lapply(SCC, class)
```

## PLOT 1: Showing the total PM2.5 emission from all sources for each of the years 1999, 2002, 2005, and 2008
# Calculate Emssions according to year
```{r}
EmissionsYear <- aggregate(Emissions ~ year,NEI, sum)
```

```{r}
barplot(EmissionsYear$Emissions/10^6, names.arg=EmissionsYear$year, col="blue", xlab='Years', ylab='Emissions (PM 2.5) in millions', main =  'Emissions (PM 2.5) per year')
dev.copy(device = png, width = 480, height = 480, file = "Plot1.png")
dev.off()
```

# Another solution using ggplot2 system (for double check)
```{r}
NEI[,6] = as.factor(NEI[,6])
library(ggplot2)
bar <- ggplot(NEI, aes(year, Emissions))
bar + stat_summary(fun.y = sum, geom = "bar") + labs (x = "Years", y = "Emissions (PM 2.5)", main =  "Emissions (PM 2.5) per year")
dev.copy(device = png, width = 480, height = 480, file = "Plot1ggplot.png")
dev.off()
```




